# ==========================================
# Macseed
# ==========================================

TOOLKIT_NAME="Macseed"
TOOLKIT_VERSION="3.4.0"

# ==========================================
# Supported macOS
# ==========================================

MIN_MACOS_VERSION="15"
